/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'milesd' at '01/09/15 13:47' with Gradle 2.2.1
 *
 * @author milesd
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
